name: notifications

description: discord notification

inputs:
  job-name:
    required: true
  status:
    required: true
  discord-webhook:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6
    - if: ${{ (inputs.job-name == 'deploy_fly' || inputs.job-name == 'deploy_render') && inputs.status == 'success' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ inputs.discord-webhook }}
        status: ${{ inputs.status }}
        content: |
          ✅ **Build suceeded!** for ${{inputs.jobs-name}}!
        description: 'notifies of status'
        color: 0x00FF2F
        url: 'https://github.com/sarisia/actions-status-discord'
        username: GitHub Actions
    - if: ${{ (inputs.job-name == 'deploy_fly' || inputs.job-name == 'deploy_render') && inputs.status == 'failure' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ inputs.discord-webhook }}
        status: ${{ inputs.status }}
        content: |
          ❌ **Build failed!** The ${{inputs.jobs-name}} pipeline encountered an error
        title: 'Failure details'
        color: 0xFF2A00
        url: 'https://github.com/sarisia/actions-status-discord'
        username: GitHub Actions
