name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check out
        run: | 
          echo "$GITHUB_WORKSPACE"
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: print date
        run: date
      - name: contents of dir
        run: |
          pwd
          ls -l
