name: notifications

jobs:
  notify:
    - uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        content: |
          Hey <@948036101346586636>.
          Job name: ${{ inputs.job-name }}
          Job status: ${{ inputs.status }}
        title: 'status'
        description: 'notifies of status'
        color: 0x0000ff
        url: 'https://github.com/sarisia/actions-status-discord'
        username: GitHub Actions
